Update for new api compatability
hc-tcg/HC-TCG-bot pull request #3
Opened 2024-11-11 23:05 UTC by Tyrannicodin

Add new api compatibility. Removes some old functionality, namely matches which may be added back later, but further api development on [hc-tcg/hc-tcg](github.com/hc-tcg/hc-tcg) will be required before it is possible.

2024-11-11 23:07 UTC, Lunarmagpie requested changes

2024-11-11 23:07 UTC, Lunarmagpie commented on exts/card.py
> +        self: "CardExt",
Its better to remove the quotes here and add `from __future__ import annotations`.
The py people are working on making it so this is standard from 3.14 onward I believe.

2024-11-11 23:20 UTC, Lunarmagpie commented on util/server.py
> +            return 0
Currently this method blocks the entire program because it is syncronous and not async.
You should be using the library aiohttp with its its asyncrounous get method for this server request to prevent the whole bot from stopping whenever anyone uses this function.
Also, its usually better to use polling for this, ie ask the server how many games are running every minute then save that. It will prevent `hc-tcg.online` form getting spammed if a ton of people use the command, which isn't really that important but its good to follow good practice.

2024-11-12 19:59 UTC, Lunarmagpie commented
FYI The endpoints you added for the bot are on production now.

2024-11-14 16:16 UTC, Tyrannicodin commented on exts/card.py
> +        self: "CardExt",
Will add in the next pr which is arrange folders, format, type checking + other cleanup.

2024-11-14 16:40 UTC, merged